name: Publish Package to Gemfury

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can change this to the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install fury CLI
      run: |
        pip install fury

    - name: Publish to Gemfury
      env:
        FURY_AUTH: ${{ secrets.GEMFURY_TOKEN }}  # Use the secret stored in GitHub Secrets
      run: |
        fury push dist/*.tar.gz dist/*.whl
